version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: gunicorn overfolio.wsgi:application --bind 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
      target: build  # build stage only (pas besoin d'exécuter nginx ici)
    container_name: frontend
    volumes:
      - frontend-dist:/app/dist  # Expose dist pour nginx
    command: sh -c "npm run build && tail -f /dev/null"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - frontend-dist:/usr/share/nginx/html  # nginx lit le dist généré
    depends_on:
      - frontend

  db:
    image: postgres:15
    container_name: db
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  frontend-dist:

